# Generated by Django 4.2.3 on 2023-07-12 00:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("LibraryApi", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Borrowings",
            new_name="Borrowing",
        ),
        migrations.RenameModel(
            old_name="Reservations",
            new_name="Reservation",
        ),
        migrations.CreateModel(
            name="Fine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fine_amount", models.DecimalField(decimal_places=2, max_digits=6)),
                ("fine_date", models.DateTimeField()),
                ("fine_paid_status", models.BooleanField(default=False)),
                (
                    "borrowing_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="LibraryApi.book",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
