# Generated by Django 4.2.2 on 2023-07-12 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("LibraryApi", "0002_rename_borrowings_borrowing_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fine",
            name="borrowing_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="LibraryApi.borrowing"
            ),
        ),
    ]
