# Generated by Django 4.2.2 on 2023-07-12 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LibraryApi", "0003_alter_fine_borrowing_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="edition",
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
