# Generated by Django 4.2.2 on 2023-07-13 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("LibraryApi", "0004_book_edition"),
    ]

    operations = [
        migrations.AddField(
            model_name="borrowing",
            name="libarian",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="libarian",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="borrowing",
            name="borrower",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="member",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
