# Generated by Django 4.2.2 on 2023-07-13 23:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("LibraryApi", "0005_borrowing_libarian_alter_borrowing_borrower"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="availabity_stautus",
            new_name="available",
        ),
        migrations.RemoveField(
            model_name="book",
            name="available_copies",
        ),
        migrations.RemoveField(
            model_name="book",
            name="copies",
        ),
    ]
