# Generated by Django 4.2.2 on 2023-07-14 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("LibraryApi", "0006_rename_availabity_stautus_book_available_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowing",
            name="borrower",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="borrower",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
